### ISSUE TITLE
compatible with cs2fixes

### ISSUE THREAD

**Issue by mihaigsm2003** [KitsuneLab-Development/K4-DamageInfo#1]
hi, nice job, but need to be compatible with [cs2Fixes](https://github.com/Source2ZE/CS2Fixes)
Thanks!

**Comment by K4ryuu** [comment]
Greetings,

CSSharp and CS2Fixes are both dynamically hooking `Host_Say` which inherently makes them incompatible.

This is currently cannot be fixed.

I keep the issue opened, because maybe at some point it could be fixed.

However I will give it a try in the upcoming days.

**Comment by K4ryuu** [comment]
Greetings,
Could you please explain the incompatibility? We dont use cs2fixes sadly.

**Comment by K4ryuu** [comment]
Hello?

**Comment by K4ryuu** [comment]
From now on CS2Fixes can be compatible with CSS overall. I close the ticket.

**Comment by mihaigsm2003** [comment]
Thanks!
