### ISSUE TITLE
[BUG] Server crash

### ISSUE THREAD

**Issue by pZyk93** [KitsuneLab-Development/K4-DamageInfo#11]
**Describe the bug**
Installed latest version of plugin, already had latest metamod + css. Server crashes within seconds of a player joining and a round has begun and you shoot someone.

**To Reproduce**
See above.

**Expected behavior**
Expected it to not crash the server and work as intended.

**Media (Optional)**
None.

**Logs (Optional)**
Cant find any logs of what causes it, but I figured I would let you know there might be an issue.

**Additional context (Optional)**
-

**Comment by K4ryuu** [comment]
Im going to investigate the problem. Do the server crash with bots also or with just players?

**Comment by pZyk93** [comment]
Only managed to test with bots so far, as soon as I shoot the first bullet it crashes.

**Comment by K4ryuu** [comment]
Are you using the latest version?

**Comment by pZyk93** [comment]
I just tried the latest version of the plugin, server crash as soon as I shot the bot, and same happened when i let bot shoot me.

Using latest metamod, css, autoupdater, k4-system and damageinfo plugins.

**Comment by K4ryuu** [comment]
The plugin has been totally remade from scratch. Please check https://github.com/K4ryuu/CS2_DamageInfo/releases/tag/v2.0.0

Best Regard,
K4ryuu
