### ISSUE TITLE
[REQ] Death summary support

### ISSUE THREAD

**Issue by iclassdon** [KitsuneLab-Development/K4-DamageInfo#15]
Add support for deathmatch.  There are no rounds.  

i.e. "death-summary-show-all-damages-enemies-only"  

The data keeps piling up on death and doesn't reset.  See below. 

▬▬▬▬▬▬▬▬▬▬▬▬▬ Statistics ▬▬▬▬▬▬▬▬▬▬▬▬▬
➜ To: [172 / 3 hits] From: [0 / 0 hits] - Gustov [22HP]
➜ To: [105 / 3 hits] From: [100 / 4 hits] - Aggressor [100HP]
➜ To: [12 / 1 hits] From: [0 / 0 hits] - Dabisi [76HP]
➜ To: [26 / 2 hits] From: [106 / 4 hits] - Comb [5HP]
➜ To: [102 / 6 hits] From: [0 / 0 hits] - Shadow [69HP]
➜ To: [125 / 12 hits] From: [232 / 10 hits] - Striker [14HP]
➜ To: [0 / 0 hits] From: [38 / 3 hits] - Bluefish [100HP]
▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬

**Comment by K4ryuu** [comment]
Hello,
There is already an option for that in the configs with the "round-end-summary-allow-death-print": true

**Comment by K4ryuu** [comment]
I just realized the second part of the request, sorry. Its too late in the morning haha

I will do it Today. Thank you!

**Comment by K4ryuu** [comment]
The feature has been added and being uploaded with next release.
