### ISSUE TITLE
plugin doesnt text nothing in chat

### ISSUE THREAD

**Issue by pur4s** [KitsuneLab-Development/K4-DamageInfo#19]
with "round-end-summary-show-all-damages": true,
plugin doesnt text nothing in chat
its my config:

// This configuration was automatically generated by CounterStrikeSharp for plugin 'K4ryuuDamageInfo', at 2024/02/11 06:35:35
{
  "round-end-summary": true,
  "round-end-summary-allow-death-print": false,
  "round-end-summary-show-all-damages": true,
  "round-end-summary-show-all-damages-enemies-only": true,
  "center-damage-info": false,
  "console-damage-info": true,
  "ffa-mode": false,
  "ConfigVersion": 2
}
idk mb some cvars they contradict each other

**Comment by K4ryuu** [comment]
Problem has been tested with the given config and solved. Going to be uploaded shortly as a new release with the other fixes.
