### ISSUE TITLE
Console Errors

### ISSUE THREAD

**Issue by itsAudioo** [KitsuneLab-Development/K4-DamageInfo#2]
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
>  ---> System.Collections.Generic.KeyNotFoundException: The given key '6' was not present in the dictionary.
>    at K4ryuuDamageInfo.DamageData.UpdateDamage(CCSPlayerController attackerController, Int32 targetId, Int32 damageHP, Int32 damageArmor, Int32 Hitgroup) in /Users/sples/Documents/GitHub/CS2_DamageInfo/src/K4ryuuDamageInfo.cs:line 141
>    at K4ryuuDamageInfo.DamageInfoPlugin.<Load>b__8_0(EventPlayerHurt event, GameEventInfo info) in /Users/sples/Documents/GitHub/CS2_DamageInfo/src/K4ryuuDamageInfo.cs:line 55
>    at InvokeStub_GameEventHandler`1.Invoke(Object, Object, IntPtr*)
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    --- End of inner exception stack trace ---
>    at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
>    at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
>    at System.Delegate.DynamicInvokeImpl(Object[] args)
>    at CounterStrikeSharp.API.Core.FunctionReference.<>c__DisplayClass3_0.<.ctor>b__0(fxScriptContext* context) in /__w/CounterStrikeSharp/CounterStrikeSharp/managed/CounterStrikeSharp.API/Core/FunctionReference.cs:line 81

I get this in my console, tryied reinstalling didn't help, sometimes plugin bugs and shows wrong or no data in chat at all

**Comment by K4ryuu** [comment]
Hello,
Which version of CSSharp and Plugin version are you using?

**Comment by itsAudioo** [comment]
Latest release of plugin, CSSharp counterstrikesharp-with-runtime-0aaad35

**Comment by K4ryuu** [comment]
After further testing, we are not facing with any source of error. Please update your CSSharp on your server and try again.
