### ISSUE TITLE
[BUG] Bug with displaying damage

### ISSUE THREAD

**Issue by itsAudioo** [KitsuneLab-Development/K4-DamageInfo#21]
![image](https://github.com/K4ryuu/CS2_DamageInfo/assets/116572799/260ade3c-bbe8-4674-a7f0-a40bb3bb1d3b)
This happened today for the first time, incorrect damage given to player(a lot more dmg than it was actually given), fixed after plugin reload :)

**Comment by K4ryuu** [comment]
This problem was solved by #20 and going to uploaded today as a new release.
Thank you!
