### ISSUE TITLE
[BUG] 5 hits in english is censored

### ISSUE THREAD

**Issue by sazarkin** [KitsuneLab-Development/K4-DamageInfo#24]
**Describe the bug**
When doing 5 hits stats show ***
```
+$300 for neutralizing an enemy
▬▬▬▬▬▬▬▬▬▬▬▬▬ Statistics ▬▬▬▬▬▬▬▬▬▬▬▬▬
➜ To: [200 / ******] From: [0 / 0 hits] - Sarge [DEAD]
▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬▬
+$3250 team income for eliminating the enemy team
```

Possible solution:
replace `hits` with `hts` for 5 :)

I guess this depends on player settings in `Settings > Communication > Text Filtering`

**Comment by K4ryuu** [comment]
I dont know what is that from, but a lot of hit stats getting censored by the game somehow. I cant do anything against it I think.

**Comment by K4ryuu** [comment]
I think the `hts` wouldnt solve the problem, since I have a translation `"phrases.center.normal": "Damage Given:\nHP {0} | Armor {1} | HitGroup: {2}"`, which is being censored in the middle randomly, if the given damage is above 110...
