### ISSUE TITLE
[REQ] Settings for killer report only

### ISSUE THREAD

**Issue by csportalsk** [KitsuneLab-Development/K4-DamageInfo#25]
Will be good for DM FFA server have option to show only report off killer. 
For DM FFA it's now possible only print all players witch get hit from player.

_Thank you_

**Comment by K4ryuu** [comment]
Why is that a wrong practice for FFA DM server to set that the player can see everyone's dmg who they hit?
Why only the killer should be shown?

**Comment by csportalsk** [comment]
It's simple. Imagine you are playing DM FFA about 12 players. You can hit 5 players or more. All info are printed on chat. Thats alot line of info in chat. DM FFA is fast and you haven't time to study all hits. Or why you need all DM hits. When you can hit lot off players when you are good. Only one is importat and who killed you. Or just connect to full DM FFA server with fast respawn and imagine the situation about lotf off unnessery line DM info. Iportant in this situation is only DMG killer player. :]

**Comment by K4ryuu** [comment]
The feature is being added in the upcoming release.
Thank you!
