### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by yizhipipihe** [KitsuneLab-Development/K4-DamageInfo#28]
plz upload

**Comment by K4ryuu** [comment]
I'm closing this issue, since it's invalid.
Upload what? The plugin can be found as source when you open the repo and you can download the built version in releases. :D

**Comment by yizhipipihe** [comment]
这是来自QQ邮箱的假期自动回复邮件。你好，我最近正在休假中，无法亲自回复你的邮件。我将在假期结束后，尽快给你回复。

**Comment by yizhipipihe** [comment]
My plugins are all installed normally, but an error is reported in the log after the turn ends




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "K4ryuu/CS2_DamageInfo"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年5月29日(星期三) 晚上11:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [K4ryuu/CS2_DamageInfo] [BUG] (Issue #28)





 
I'm closing this issue, since it's invalid.
 Upload what? The plugin can be found as source when you open the repo and you can download the built version in releases. :D
