### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by fpaezf** [KitsuneLab-Development/K4-DamageInfo#29]
Installed the plugin but only get chat statistics, not center screen message, how i can enable it?
I'm on default config, i didn't touch anything.

**Comment by fpaezf** [comment]
CFG:

`// This configuration was automatically generated by CounterStrikeSharp for plugin 'K4ryuuDamageInfo', at 2024/08/16 10:36:09
{
  "round-end-summary": true,
  "round-end-summary-allow-death-print": true,
  "round-end-summary-show-only-killer": false,
  "round-end-summary-show-friendlyfire": false,
  "round-end-summary-show-all-damages": false,
  "round-end-summary-show-all-damages-enemies-only": true,
  "center-damage-info": true,
  "console-damage-info": true,
  "ffa-mode": false,
  "norounds-mode": false,
  "center-info-flags": [
    "@myplugin/can-see-permission",
    "#myplugin/can-see-group",
    "can-see-override",
    "leave-empty-so-let-everyone-see"
  ],
  "ConfigVersion": 4
}`

**Comment by K4ryuu** [comment]
Until you have values in `center-info-flags`, only people with those permissions can see that center message. Make its value to [] in order to show it to everyone. This is why they all says "myplugin" as they are just examples.

**Comment by fpaezf** [comment]
Worked. Thank you!
