### ISSUE TITLE
does this plugin show live hp hits ?

### ISSUE THREAD

**Issue by mayersgamer** [KitsuneLab-Development/K4-DamageInfo#30]
does this plugin show live hp hits ? or just after rounds ? because when i shoot and hit i see no damage info

**Comment by K4ryuu** [comment]
It does display live info on center of the screen if enabled or in console of player aswell.

**Comment by mayersgamer** [comment]
not for me and my players it only show after the death in the chat and in console , do i need to activate it in the config file ?

i hope we understand each other im looking for the live hp hit of the other player for example if i hit a grenade and hit an enemy it will show me damage given to him , like old times with cs 1,6 plugins

**Comment by K4ryuu** [comment]
Cu you didnt remove the flags from the center message permissions. :)
Make it empty to let everyone see it.

There is realtime data, just your config is bad.

**Comment by mayersgamer** [comment]
thank you
can i modify it to only show hp hit ? and not tell about leg or hand hit

**Comment by mayersgamer** [comment]
hello man , i like your plugins and your time spent on it , butt can you tell me what to do . i have a case in which a guy that i bbanned is ddosing my server 
example : 
https://youtu.be/3MkUs3MWQI0

my server is hosted qonzer which provide ddos protection .

is there an anti flood plugin out there or a way to stop him from taking my server resources ? some times my dedicated core is 100% abused by him and and internet used is reaching 500mb , diffrent ip adress from usa and germany and china .

this dude is abusing my server every day.

**Comment by mayersgamer** [comment]
another idea we need plugin that slays ct for not defusing and t for not planting after timeover

**Comment by K4ryuu** [comment]
It's nothing to do with damage statistics
