### ISSUE TITLE
Update

### ISSUE THREAD

**Issue by jxn78** [KitsuneLab-Development/K4-DamageInfo#31]
Pls update

**Comment by K4ryuu** [comment]
Update with what? Next time if you open an issue, make it to have some context and sense. :D

**Comment by jxn78** [comment]
![IMG_20241004_181623](https://github.com/user-attachments/assets/962ec295-96e1-4707-a4b4-ce28e37cccf7)
is this not a bug in your plugin? Or not?😄

**Comment by K4ryuu** [comment]
I'll check it on our dev, if its plugin issue or not

**Comment by raszyniaczek** [comment]
Only this plugin doesnt work after new update :)

**Comment by K4ryuu** [comment]
The issue has been fixed, but upgrading the plugin visually a bit, then pushing the update.
I had tons of tasks, so thanks for the patience!

The release will be out within an hour max.
