### ISSUE TITLE
[BUG] Language file loading error

### ISSUE THREAD

**Issue by 577fkj** [KitsuneLab-Development/K4-DamageInfo#32]
**Describe the bug**
Language file loading error

![image](https://github.com/user-attachments/assets/39e2b503-5e9d-4a27-a62a-d181274fcce7)
The language files were also checked and no issues were found.
How can I troubleshoot this issue? Other plugins have not encountered this problem.

**Comment by K4ryuu** [comment]
Upload the langs folder with the plugin. You should upload all files that you download from releases. Also if you set your server language to another language from "en", then your lang folder should have that language translation aswell.
