### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by mrdiega** [KitsuneLab-Development/K4-DamageInfo#4]
1.3.0 version
crash server after first kill or death

**Comment by K4ryuu** [comment]
Greetings,

1. If you send a bug report, follow the given template, which is loaded by default into the message and give a title after the BUG prefix.

2. Try to update your CSSharp version to atleast the MinimumAPIVersion.

3. If the 2. didnt fix the problem and you have the correct version of the CSSharp, attach some kind of log, server console error.

Best Regards,
K4ryuu

**Comment by mrdiega** [comment]
> Greetings,
> 
> 1. If you send a bug report, follow the given template, which is loaded by default into the message and give a title after the BUG prefix.
> 2. Try to update your CSSharp version to atleast the MinimumAPIVersion.
> 3. If the 2. didnt fix the problem and you have the correct version of the CSSharp, attach some kind of log, server console error.
> 
> Best Regards, K4ryuu
OC Debian 11
Metamod:Source version 2.0.0-dev+1256
counterstrikesharp-build-12-a0f9d30.zip
[#9]: "Damage Info" (1.3.0) by K4ryuu
Crash server after first kill or death
There is no crash on early versions, but for some reason damage information is not displayed in the chat with `RoundEndPrint": true`

**Comment by mrdiega** [comment]
> Greetings,
> 
> 1. If you send a bug report, follow the given template, which is loaded by default into the message and give a title after the BUG prefix.
> 2. Try to update your CSSharp version to atleast the MinimumAPIVersion.
> 3. If the 2. didnt fix the problem and you have the correct version of the CSSharp, attach some kind of log, server console error.
> 
> Best Regards, K4ryuu

OC Debian 11
Metamod:Source version 2.0.0-dev+1256
counterstrikesharp-build-12-a0f9d30
[#9]: "Damage Info" (1.3.0) by K4ryuu

Crash server after first kill or death
There is no crash on early versions, but for some reason damage information is not displayed in the chat with `"RoundEndPrint": true` (tested with bots)

**Comment by y3request** [comment]
Not sure if this is the right place, but I had this happen too. 
All I did was disable another plugin (advertisement) from writing on center screen, while the damage plugin is trying to write dmg center screen. 
No more crashes.

**Comment by K4ryuu** [comment]
Greetings,
We are going to look after the mentioned problem and we appreciate your feedback about the possible problem.

**Comment by fpaezf** [comment]
> Not sure if this is the right place, but I had this happen too. All I did was disable another plugin (advertisement) from writing on center screen, while the damage plugin is trying to write dmg center screen. No more crashes.

I have advertisment too and only writing on chat.
Same crash on first hit.
Any clues?

CS2_DamageInfo 1.3.2
CounterStrikeSharp v52
Metamod:Source version 2.0.0-dev+1259

**Comment by K4ryuu** [comment]
The plugin has been totally remade from scratch. Please check https://github.com/K4ryuu/CS2_DamageInfo/releases/tag/v2.0.0

Best Regard,
K4ryuu
