### ISSUE TITLE
[BUG] Alive player HP always says 0 HP

### ISSUE THREAD

**Issue by Ganji89420** [KitsuneLab-Development/K4-DamageInfo#8]
**Describe the bug**
Always says 0HP on attacker that is alive at the end of the round damageinfo in chat display

**Expected behavior**
Should say remaining HP

Screenshot shows WOLF killed me, Wolf is still alive, and damage info in chat shows 0HP.
![DamageIND 0 HP](https://github.com/K4ryuu/CS2_DamageInfo/assets/151049632/53e779cf-b0ed-44f5-ba08-a10efae9a54c)

**ALSO DAMAGE DOESNT LINE UP WITH WHAT THE GAME SAYS AT THE TOP**

**Comment by asdfxD** [comment]
same issue here, it counts a bit wrong at the top, maybe its because of players armor?

![damage](https://github.com/K4ryuu/CS2_DamageInfo/assets/24253340/dbdc0c29-7690-4d80-ba4d-1bd17c1a1498)

**Comment by asdfxD** [comment]
any new info about it? i really love this plugin.

**Comment by K4ryuu** [comment]
The plugin has been totally remade from scratch. Please check https://github.com/K4ryuu/CS2_DamageInfo/releases/tag/v2.0.0

Best Regard,
K4ryuu
