### ISSUE TITLE
[BUG] First shot on Damage Indicator says over 100

### ISSUE THREAD

**Issue by Ganji89420** [KitsuneLab-Development/K4-DamageInfo#9]
**Describe the bug**
First shot from damage indicator comes back as over 100 but its not correct.

**To Reproduce**
1. Buy ak
2. Shoot enemy one time
3. See error damage comes back as incorrect.

**Expected behavior**
Should show accurate damage

**Media (Optional)**
FIRST SHOT SHOWS 118 Damage but that isnt correct. there is no kill.
![First Shot damage bug](https://github.com/K4ryuu/CS2_DamageInfo/assets/151049632/6c553813-a25c-4758-b6eb-22af03a87dd5)

**Comment by Ganji89420** [comment]
One shot, with pistol in the head, comes back 156 damage, but no kill.
![Counter-strike 2 Screenshot 2023 11 16 - 11 45 58 90](https://github.com/K4ryuu/CS2_DamageInfo/assets/151049632/254d24e4-6541-4d66-82ac-cf462508c56f)

**Comment by Ganji89420** [comment]
ak, 132 damage in left arm, no kill
![Uploading ak 132dmg.png…]()

**Comment by Ganji89420** [comment]
ak 132 damage on right arm, no kill
![ak 132dmg](https://github.com/K4ryuu/CS2_DamageInfo/assets/151049632/2f087b59-584e-4253-bee6-80b5fc731080)

**Comment by K4ryuu** [comment]
Greetings,
Today I'm checking on it

**Comment by K4ryuu** [comment]
The plugin has been totally remade from scratch. Please check https://github.com/K4ryuu/CS2_DamageInfo/releases/tag/v2.0.0

Best Regard,
K4ryuu
